[package]
name = "springd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive", "cargo", "env"] }
clap-duration = "0.1.11"

[[bin]]
name = "springd"
